### PR TITLE
update windows wheel to latest stable FreeTDS

### PR DESCRIPTION
**Pull request by jpgimenez**
use statically linked FreeTDS 1.00.78
remove openssl installation on windows
update python versions

### CODE REVIEW

**Comment by rsyring** [comment]
@jpgimenez Sorry for the delay in getting to this review.  Can you please explain why you are making the changes you are making.  In particular, why are you removing OpenSSL?

**Comment by jpgimenez** [comment]
@rsyring last windows wheels (2.1.3) are already build that way:

> Version 2.1.3 - 2016-06-22 - Ramiro Morales
>
>    We now publish Linux PEP 513 manylinux wheels on PyPI.
>    Windows official binaries: Rollback changes to Windows binaries we had implemented in pymssql 2.1.2; go back to using:
>        A statically linked version of FreeTDS (v0.95.95)
>        No SSL support

I'm updating to latest FreeTDS and I keep the nossl support because statically linking ssl doesn't look like a good idea. I can work later on wheels with support for dynamically linked openssl, but that adds a dependency for the installation on windows that not everybody wants, and could be an issue for people upgrading from previous versions. IMO having support for ssl on windows is good, but the main wheels needs to keep without it for now...

**Comment by jpgimenez** [comment]
@rsyring I'll merge this to a new branch inside the project, so travis build could run because in this PR is failing with this message:
> $TRAVIS_SECURE_ENV_VARS is set to "false"; probably running in a pull request from a fork; this is not supported by Travis CI.

**Comment by fastviper** [comment]
This solves problem with 'pip install pymssql` everyone is having. Pretty please, with sugar on top: include this in main distribution and do not force beginner python programmers to learn how to install freeTDS in Windows for headers to be visible to VS and so on. We already are miserable without linux, please do not make us suffer, have mercy.

**Pull request merged**
