### PR TITLE
Fix windows wheel builds

### PR DESCRIPTION
**Pull request by PrimozGodec**
Making way for Windows wheels https://github.com/pymssql/pymssql/issues/839

Changes:
- Windows x86: Use older OpenSSL since the newest does not install on x86 systems (choco issue, already reported)
- Windows x64: Fixing path to OpenSSL library since it seems the installation location changed.

### CODE REVIEW

**Comment by PrimozGodec** [comment]
@termim, can you please approve the workflow run? I would like to work towards Windows build working again.

**Comment by PrimozGodec** [comment]
It seems this PR fixes the Windows build: https://github.com/PrimozGodec/pymssql/actions/runs/5876037350.
@termim, can you merge and also upload Windows wheels to PyPI?

**Comment by termim** [comment]
Good catch! Please remove the unnecessary import.

2.2.8 windows wheels are on PyPI already.

**Comment by PrimozGodec** [comment]
Done. :)

**Pull request merged**
