### PR TITLE
Support bulk copy.  Fixes #279

### LINKED ISSUE #279: Support bulk load protocol like bcp uses?
We have a project coming up to migrate some legacy code that is currently shelling out to bcp.  I've been thinking this might be a good opportunity to enhance pymssql to give it the ability to bulk-load data.  Anyone know anything about how this might work and/or if freetds has support for this?

### PR DESCRIPTION
**Pull request by SimonStJG**

### CODE REVIEW

**Comment by SimonStJG** [comment]
Given some of the google groups posts, I wasn't sure if this project is still in active development?  If it is, and you're interested in this feature, I'll write the docs updates too.

**Comment by termim** [comment]
I would not cal it very active development but it is still alive. You contribution is very welcome and if you could write documentation as well that would be great!

**Comment by SimonStJG** [comment]
I had to choose a "versionadded" for the new feature in the docs update, so chose 2.2.0 which would be a minor version bump

**Comment by termim** [comment]
Thank you!

**Pull request merged**
