### PR TITLE
install Cython if not already installed, Issue #578

### PR DESCRIPTION
**Pull request by adriannye**
This installs cython using a subprocess if the import of cython fails.

### CODE REVIEW

**Comment by adriannye** [comment]
This patch allows pymssql to build successfully on OSX using tox, by completely installing Cython if it's not already installed before continuing to install requirements.  However it doesn't build in the CI system because it doesn't find sqlfront.h, which I believe is defined in freetds-devel.  Not sure how to resolve this correctly.

**Comment by AlexHagerman** [comment]
Does having Cython in `setup_requires` or `install_requires` not work? Also it looks like you're doing this against `master` we are in the process of getting `2.1.x` CI updated. Active development is happening against that branch. Master/2.1.x plans are in progress, but if you are using master this will be on hold for a little bit.

**Comment by adriannye** [comment]
Having Cython in install_requires works, see adriannye/pymssql@cython_macosx_from_2.1.x which is also branched from your active development branch.

Having Cython in setup_requires, according to the doc, wouldn't work, it says: "Note: projects listed in setup_requires will NOT be automatically installed on the system where the setup script is being run. They are simply downloaded to the ./.eggs directory if they’re not locally available already. If you want them to be installed, as well as being available when the setup script is run, you should add them to install_requires and setup_requires.)"

**Comment by adriannye** [comment]
I tried setup_requires and install_requires and neither worked separately or together.

**Comment by adriannye** [comment]
I've closed this and will open another against the correct branch.

**Pull request closed without merging**
