### PR TITLE
fix memory leak when connection fail for any reason

### PR DESCRIPTION
**Pull request by caogtaa**
When connect db failed, `MSSQLConnection._connected` is still 0. In such case if connection object is not reused, native memory allocation in `MSSQLConnection.__cinit__()` is not freed in `MSSQLConnection.__dealloc__()`,  `MSSQLConnection._connected == 0` just skip the actual memory free.

### CODE REVIEW

**Comment by heng4fun** [comment]
Look good to me

**Comment by AlexHagerman** [comment]
FYI sorry I was traveling this week I'll check this out on Monday.

**Comment by caogtaa** [comment]
> FYI sorry I was traveling this week I'll check this out on Monday.

Have a good time :)

**Comment by AlexHagerman** [comment]
This looks good, but let me get the CI failures sorted out before a final merge.

**Comment by ocalvo** [comment]
Is this still have CI issues?

**Comment by termim** [comment]
Fixed in #690

**Pull request closed without merging**
