### PR TITLE
Faster implementation of Cursor.executemany

### PR DESCRIPTION
**Pull request by klothe**
This fixes the slow implementation of Cursor.executemany as described in https://github.com/pymssql/pymssql/issues/332 by combining all parameter lists for an INSERT statement into one statement, which gets executed in a single round trip to the server.

There is still a maximum of 1000 parameter lists per insert.

I wish this could be done without parsing SQL, but I don't see any way to avoid it. (Thanks to MySQLdb for the regular expression.)

### CODE REVIEW

**Comment by rsyring** [comment]
Thanks @klothe.  Did you look to see if there are tests covering execute many functionality?

**Comment by klothe** [comment]
There was test_pymssql.TestCursor.test_execute_many, which only had a DELETE statement. I renamed that to test_executemany_delete and added a new one with an INSERT statement called test_executemany_insert, there's one with "VALUES" in it and one without.

I would like to make sure all the new code is covered by tests, but I'm not sure how to see the coverage in a .pyx file.

**Comment by msabramo** [comment]
@sontek: Does this speed up your stuff?

**Comment by sontek** [comment]
I don't use execute many, I need the serialization itself sped up

**Comment by klothe** [comment]
Has anyone been able to review this so far? I think my tests are sufficient but I’m happy to make any changes that are necessary.

**Comment by Warfront1** [comment]
@group can someone please review this, thanks @klothe . I was not even aware of this bug. After implementing your code manually, I was getting astronomically better insert rates. It opens pymssql up for some ETL operations that just aren't feasible with the currently bugged implementation of the function.

**Comment by ramiro** [comment]
I'll try to take a look at this over the weekend.

On Wed, Nov 11, 2015 at 5:55 PM, Warfront1 <notifications@github.com> wrote:

> @group <https://github.com/group> can someone please review this, thanks
> @klothe <https://github.com/klothe> . I was not even aware of this bug.
> After implementing your code manually, I was getting astronomically better
> insert rates. It opens pymssql up for some ETL operations that just aren't
> feasible with the currently bugged implementation of the function.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pymssql/pymssql/pull/333#issuecomment-155907003>.
>



-- 
Ramiro Morales
@ramiromorales

**Comment by Warfront1** [comment]
@ramiro were you able to look over the pull request this past weekend?

**Comment by vadoverde** [comment]
Wanted to share this XML solution I developed for this issue as it helped others. I hope it helps:
https://gist.github.com/vadoverde/84f4d4a4c31416d2dfee

**Comment by Warfront1** [comment]
@vadoverde  Thanks for the solution. 
I've personally just generated the string using .format and sending bulks of around 950 to an execute.
@group @ramiro any visibility into the status of this bug report?

**Comment by rsyring** [comment]
@bladams when you are doing pymssql work this month will you please see if you can get this issue resolved?

**Comment by ramiro** [comment]
Added tests fail showing things aren't working under Python 3.x e.g. https://travis-ci.org/pymssql/pymssql/jobs/96643502

(I've created PR #357 which is a clone of this PR but in which the CI setups actually run.)

**Comment by bladams** [comment]
I'm not sure it's a good idea for pymssql to rewrite statements to such an extent. It seems to me like this is more of a query generation issue. On the other hand this really isn't that much different from the parameter replacement, I suppose. 

I looked into psycopg's execute many implementation and it appears to be executing each statement in a loop like pymssql's current implementation https://github.com/psycopg/psycopg2/blob/master/psycopg/cursor_type.c#L547

I'll try to fix the failing test and add a couple more tomorrow.

**Comment by termim** [comment]
A batch optimization is implemented in https://github.com/pymssql/pymssql/commit/4866d619d62782f8b6b579d0441c3defb90e712e it is safer and more general.

**Pull request closed without merging**
