### PR TITLE
Added support for date, time, and datetime2.

### PR DESCRIPTION
**Pull request by epa**
https://github.com/pymssql/pymssql/issues/156

### CODE REVIEW

**Comment by damoxc** [comment]
I think it would be prudent to add a check to see what version of FreeTDS is being compiled against before adding these types, unless of course you have tested what happens when this is compiled against an older version of FreeTDS? At the very least some unit test coverage would be good :) Thanks!

**Comment by epa** [comment]
I don't believe it matters if the code is compiled against an older FreeTDS version, since the new types will simply not be returned in that case.  (Older FreeTDS versions, or newer ones with TDSVER set below 7.3, will return these date and type columns as strings.)

For test coverage, is it OK to write a test which won't run on older MSSQL versions?

**Comment by epa** [comment]
Tests added - please have a look.

**Comment by epa** [comment]
Hi, have you had time to look at the new merge request including tests?

**Comment by rsyring** [comment]
@epa sorry, we don't have a lot of active developers right now.  It may take some time for this to get reviewed and released.

Concerning testing for older versions of SQL Server.  It would be better if the tests checked for the sql server version and used pytest.mark.skipif(...) to skip the test if the version is too old.

**Comment by epa** [comment]
Yes, I'll add the skipif.  Do you know how to test the version of SQL Server?

**Comment by rsyring** [comment]
Something based on `@@VERSION` I'd guess: https://msdn.microsoft.com/en-us/library/ms177512.aspx

**Comment by rsyring** [comment]
Something based on `@@VERSION` I'd guess: https://msdn.microsoft.com/en-us/library/ms177512.aspx

You could also check out SQLAlchemy code.  I'd bet it has some code for getting the version out of MSSQL and comparing for testing/feature support.

**Comment by ramiro** [comment]
Merged in 97129dfaea435ba04f977198b9f086baf6dc8a66

**Comment by epa** [comment]
Thanks for merging this, sorry I didn't get around to making the tests conditional.

**Pull request closed without merging**
