### PR TITLE
Add section about username and password's lenght

### PR DESCRIPTION
**Pull request by labynocle**
Hi there,

It's a simple PR to update the FAQ by adding a limit which is currently not documented (about the username and password's lenght).
It's just to avoid people being crazy by debugging it (like I did :) )

Hope it will help people!

### CODE REVIEW

**Comment by ramiro** [comment]
What version of freeTDS are you using?

This ticket/thread[1] and this commit[2] would suggest there is no 30-character limit for passwords anymore since FreTDS 0.91, even for DB-Lib:

1. https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=706388
2. https://github.com/FreeTDS/freetds/commit/50390173fb2022fda1e2b241d5817ac1d08f386a

**Comment by ramiro** [comment]
I see we already discused this on isue "246 which you rightly reference.

**Comment by labynocle** [comment]
My env is as following:

```
$ dpkg -l | grep freetds
ii  freetds-bin                    0.91-6+b1                   amd64        FreeTDS command-line utilities
ii  freetds-common                 0.91-6                      all          configuration files for FreeTDS SQL client libraries
ii  freetds-dev                    0.91-6+b1                   amd64        MS SQL and Sybase client library (static libs and headers)

$ pip freeze 2> /dev/null | grep pymssq
pymssql==2.1.2
```

**Comment by ramiro** [comment]
My bad, this is fixed in FreeTDS 0.95 (released on june 2015), not 0.91 (releases on 2011) as I wrongly stated above.

I think this would need to be the main take away for the new FAQ entry: This is a solved FreeTDS problem but you need to be using FreeTDS 0.95 or newer, if you are stuck with 0.91 then keep in mind this limitation, even when you can get usernames, passwords longer than 30 to work on tsql.

Also, I'd drop the links to the github issues (we can add them to the changelog.)

Thanks for your contribution!

**Comment by labynocle** [comment]
Sorry I should precis it.
Unfortunately in my case I'm stuck with the described versions.

I let you make the new commit with the changes ?

thank you for the quick feedback :)

**Comment by jpgimenez** [comment]
Added the message on commit 81735820a038fb3dfc4b56fef4d4267e644bc363, will be part of 2.1.4 release.

**Pull request closed without merging**
