### PR TITLE
Free MSSQLConnection memory in dealloc rather than mark_disconnected

### PR DESCRIPTION
**Pull request by SimonStJG**
Prevents memory leak on e.g. login failure during __init__

### CODE REVIEW

**Comment by SimonStJG** [comment]
Similar to PR 640 but I think it's neater to free in dealloc, plus using dealloc to free memory initialised in cinit is a pattern cython recommends - https://cython.readthedocs.io/en/latest/src/userguide/special_methods.html#finalization-method-dealloc

**Comment by termim** [comment]
Could you also create a test case for this?

**Comment by SimonStJG** [comment]
To prove that it isn't leaking memory?  If so I don't know of a neat way to do this - the only ways I know of to test for memory leaks is using heavyweight stuff like valgrind - do you have a suggestion?

**Comment by termim** [comment]
I've added simple memory leak test for unsuccessful connections. It failed before your PR and is passing now :)
Thanks for the patch.

**Pull request merged**
