### PR TITLE
Add Dockerfile

### PR DESCRIPTION
**Pull request by msabramo**
for building Ubuntu [Docker](https://www.docker.com/) images with pymssql and [FreeTDS](http://www.freetds.org/) pre-installed.

### Download the image ###

    docker pull pymssql/pymssql

### Run the image ###

    docker run -it --rm pymssql/pymssql

By default, if no command is specified, an [IPython][1] shell is invoked. You can override the command if you wish -- e.g.:

    docker run -it --rm pymssql/pymssql bin/bash

## Example usage ##

    $ docker pull pymssql/pymssql
    ...
    $ docker run -it --rm pymssql/pymssql
    Python 2.7.6 (default, Mar 22 2014, 22:59:56)
    Type "copyright", "credits" or "license" for more information.
    
    IPython 2.1.0 -- An enhanced Interactive Python.
    ?         -> Introduction and overview of IPython's features.
    %quickref -> Quick reference.
    help      -> Python's own help system.
    object?   -> Details about 'object', use 'object??' for extra details.
    
    In [1]: import pymssql; pymssql.__version__
    Out[1]: u'2.1.1'
    
    In [2]: import sqlalchemy; sqlalchemy.__version__
    Out[2]: '0.9.7'

    In [3]: import pandas; pandas.__version__
    Out[3]: '0.14.1'

  [1]: http://ipython.org/

I've uploaded a Docker image using this branch to the Docker Registry at:

https://registry.hub.docker.com/u/pymssql/pymssql/

Cc: @ramiro, @rsyring, @damoxc, @sontek, @aconrad

### CODE REVIEW

**Comment by ramiro** [comment]
@msabramo Is this up to date and so in mergeable state?

**Comment by msabramo** [comment]
Hmmm, let me see...

**Comment by msabramo** [comment]
Hmmm, I never documented it, as you suggested, but now that I'm looking at the docs, I'm having a hard time finding a place to fit it since we don't really have a section about how to install pymssql (!) so I just opened a PR for that -- https://github.com/pymssql/pymssql/pull/319

**Comment by msabramo** [comment]
Ok, now I have instructions in `intro.rst`, but I need to add an entry to `Changelog`.

**Comment by msabramo** [comment]
And I need to rebase on master

**Comment by msabramo** [comment]
@ramiro: Okay, I rebased and updated `ChangeLog`. How does this look now? Okay to merge?

**Comment by ramiro** [comment]
@msabramo IMHO this is in :shipit: state.

**Comment by msabramo** [comment]
OK, merged this and posted about it at:

* https://groups.google.com/forum/?fromgroups#!topic/pymssql/ltqyjF5UBjw
* http://marc-abramowitz.com/archives/2015/04/09/pymssql-and-docker/

**Pull request merged**
