### PR TITLE
update windows wheel to latest stable FreeTDS

### PR DESCRIPTION
**Pull request by jpgimenez**
use statically linked FreeTDS 1.00.78
remove openssl installation on windows
update python versions

merge the changes build in my fork, its the same PR #522 but in this one travis build should run.

### CODE REVIEW

**Comment by jpgimenez** [comment]
On commit 224b32f I fixed a test that was failing when running on appveyor, with the latest FreeTDS the test for "Repeated failed connections" was getting hang waiting for a response, changing the server from "www.google.com" to "github.com" the test worked as expected. I'm not sure about what was changed on FreeTDS to cause this, but I think that the goal of the test is check that error messages don't get duplicated, not to check if connecting to an invalid http server is raising an error.

**Comment by rsyring** [comment]
@jpgimenez: I'm not sure I can give you much of a review on this.  I don't use Windows.

Will this PR address and/or close any issues that are currently open?  If so, can we get the description of the PR to include:

```
refs #xxx - [issue subject]
fixes #xxx - [issue subject]
```
etc?

Once that is done, if you have any concerns about the PR, we could point people on those issues to this PR and ask them to try/test the build from AppVeyor?  Could do the same for the mailing list.

Thanks for your efforts on this.

**Comment by jpgimenez** [comment]
this PR addresses issues installing pymssql on windows,
refs:
  #510 - [VS2017 Enterprise, Python 3.6 Virutal Environment and .whl file installation ]
  https://github.com/pymssql/pymssql/issues/473#issuecomment-276569713 - [Wheels for Python 3.6] (for windows only)

I'll work for updated wheels for linux too, on a separate PR.

**Comment by jpgimenez** [comment]
@rsyring if there is no complains I'll merge this to master, I already created a similar PR (#527) for linux wheels, after both PRs are merged on master we can make a new release that is linked against latest stable FreeTDS.

**Pull request merged**
