### PR TITLE
Set FreeTDS relative repository path

### PR DESCRIPTION
**Pull request by allanadair**

### CODE REVIEW

**Comment by allanadair** [comment]
Looks like the CI configurations need some updating. The change only affects the build when `PYMSSQL_BUILD_WITH_BUNDLED_FREETDS` is set.

**Comment by AlexHagerman** [comment]
Since we are using the latest stable FreeTDS release in our CI builds now this actually causes them to break. The FreeTDS 0.95 artifact in the repo is for those who need that older version and want to build `pymssql` on their own with that version.

For release we will continue to use the latest stable to keep things up to date.

Appreciate the PR and keeping an eye out. If there are any open issues you would like to tackle but need help with feel free to tag me and I'll help you get started on it.

**Comment by allanadair** [comment]
Does this mean that there will no longer be a bundled FreeTDS?

**Comment by AlexHagerman** [comment]
Since we are distributing wheels does it need to be bundled? As mentioned the version in the repo is there for those that are doing a manual build and that would be for backwards compatibility reasons to my understanding. Are you running into an issue? If so can you open an Issue on here with the version and platform information so we can look at our options for fixing it?

**Comment by allanadair** [comment]
#527 broke the ability to build with the bundled FreeTDS by moving the artifacts from `.freetds/*` to `freetds0.95/*` this PR addresses that breaking change.

**Comment by allanadair** [comment]
Actually, I see where there was a a problem in the PR.

**Pull request closed without merging**
