### PR TITLE
Python 3.8 Support

### PR DESCRIPTION
**Pull request by PH89**
- Removing printing of platform.linux_distribution()

### CODE REVIEW

**Comment by decaz** [comment]
@n0mn0m can you merge it and release a new version, please?

**Comment by n0mn0m** [comment]
@decaz https://github.com/pymssql/pymssql/issues/576

**Comment by cmccandless** [comment]
Update on this issue?

**Comment by The-Compiler** [comment]
@cmccandless #668

**Comment by termim** [comment]
@PH89 Could you please rebase

**Comment by termim** [comment]
Merged, thank you!

**Comment by PH89** [comment]
@termim So will this project continue ?

**Comment by termim** [comment]
Yes, I'll try to update it to the latest Python and fix some obvious bugs.

**Pull request merged**
