### PR TITLE
Hotfix set path to freetds0.95 for PYMSSQL_BUILD_WITH_BUNDLED_FREETDS

### PR DESCRIPTION
**Pull request by allanadair**
See closed #589

### CODE REVIEW

**Comment by allanadair** [comment]
Hi, there are some CI things that I think are not working as intended.

- CircleCI seems to fail because it does not have Cython pre-installed, which I think is known at #578. 
- TravisCI tries to do something with secrets (deploy to PyPI?) which is not allowed for pull-requests according to the logs. But the build is otherwise successful from what I can tell. It even sets the environment variable `PYMSSQL_BUILD_WITH_BUNDLED_FREETDS=1`, so that might be interesting.


It might be nice if there were an install error when `PYMSSQL_BUILD_WITH_BUNDLED_FREETDS=1` but the build actually uses a non-bundled version of FreeTDS. It looks like this has been happening for other builds on TravisCI (e.g. #587). Should I create an issue for that?

**Comment by AlexHagerman** [comment]
Hi Allan,

The TravisCI issue is a known issue. If you google TravisCI PR from Fork security issue there's plenty that can be read about. That's why we are switching to Circle. You can see the Circle build process here:

https://circleci.com/gh/pymssql

You can also see that outside of your PR and the PR about Cython (which has an outstanding sync issue) that the build is working. We used the builds for 2.1.4 available on PyPi.

You didn't answer my questions on the last ticket so I'll add a couple here:

1. Why do you need FreeTDS bundled in the Github repo? While it was done historically it's not a practice that I believe should be continued for similar reasons to why we don't have Cython in this repo.
2. The PR you called out as an issue is 7 months old, why is this only now popping up?
3. Does the wheel cause an error for you?
4. Are you avoiding a pip install and manually building for a reason? 

Historically prior to wheels FreeTDS was in the repo. I think that's what you mean by bundled, but that's not really bundled in the sense of how a wheel works it's just a copy of another repo or artifacts in this repo. That's a legacy component left in case somebody wants to manually build on their own. We won't rename that so that people know it is FreeTDS 0.95 not the up to date 1.x release of FreeTDS. We don't want to rely on outdated releases in our build forever either. If you follow the FreeTDS repo you can see them finding and correcting issues from time to time. Whenever we make a new release we want to take advantage of those updates if they are in the stable release.

Can you please let me know what it is you're trying to do, or what issue this is causing you so we can have the correct solution.

**Comment by AlexHagerman** [comment]
@allanadair thanks for the extra information.

The CircleCI build is available in stable-2.1.x not master today. There's an open issue (#569) around master and the current stable-2.1.x branch where dev is happening. If you checked out from master then you are missing the `.circleci` directory and that is why it's failing. I need to get more details on what the version switch on master from 2.1 to 2.2 was which I'll be digging into next month.

The stable-2.1.x branch also has build scripts in `/dev`. One of the reasons we are changing things is because of the `manylinux` pep. We wanted to get a CI pipe back up and running completely compatible with that. During that is when we made the FreeTDS change. You can see in AppVeyor and CircleCI where that is being downloaded. For Windows we grab the FreeTDS artifact. For Linux we download stable and build.

https://github.com/pymssql/pymssql/blob/stable-2.1.x/dev/build_manylinux_wheels.sh
https://github.com/pymssql/pymssql/blob/stable-2.1.x/dev/build_freetds_linux.sh

Finally, I think looking at this the solution maybe for us to just use a wildcard for FreeTDS when the `PYMSSQL_BUILD_WITH_BUNDLED_FREETDS` flag is set. That way it will pick up FreeTDS when we download it for CI, or when somebody is building with `freetds0.95` from the repo. 

Let me know your thoughts on that. If it works and fixes the issue then please do a PR based on stable-2.1.x to stable-2.1.x with a wildcard instead of the specific directory name. Something like `freetds*' should work. I believe the last time I looked at fpath it was a custom function, but don't remember all the details so if you need help just let me know.

**Comment by AlexHagerman** [comment]
@allanadair I think all of that sounds great. I know Python packaging, versions and Cython has changed quite a bit since the original 2.x.x rewrite of pymssql. With 2.1.4 the goal was to get CI/CD and any breaking issues updated enough for a a new release. Going forward I think there is room for us to work on refactoring and making things more straightforward for the library, build etc.

Look forward to the issues. Appreciate your help and feedback. The more people we have involved the better the package will be.

**Pull request closed without merging**
