### PR TITLE
Alpine docker image for Python 3.7 and pymssql

### PR DESCRIPTION
**Pull request by bugra**
- Adds an alpine docker image for `pymssql`

### CODE REVIEW

**Comment by AlexHagerman** [comment]
Thanks @bugra I'll check this out when I start back on ticket #558 after the 2.1.4 release is done. This image looks like it's built for more than pymssql though? I see kafka for instance, but maybe I'm missing something.

**Comment by bugra** [comment]
@AlexHagerman Sure, np.

Yes, that is correct. I have this library which depends on pymssql: https://github.com/jet/baybars

I want to provide an Alpine docker image which is essentially on preparing dependencies for `baybars`. 

What would be the time when we can `pip install pymssql`? I can help `pymssql` pip installable if there is something I can do.

**Comment by AlexHagerman** [comment]
@bugra we are working through some transitions on the CI/CD front, but hope to have an RC on pypi for review this week and then a 2.1.4 release shortly after. We have a couple CD settings blocking RC deployment. Once that is cleared up we will have the RC up.

Version `2.1.3` is on pypi https://pypi.org/project/pymssql/ which you can `pip` install today.

We also have a ticket open for transitioning to CircleCI for our builds. Since we will use docker there I think we can consider the ability for multiple build images. Initial PR is here https://github.com/pymssql/pymssql/pull/567 issue here https://github.com/pymssql/pymssql/issues/562 your image needs to be able to build and run the pymssql test suite if the goal is validating pymssql on alpine. If your wanting to do more than validate the build and test on alpine for `pymssql` (for instance validate a kafka component) that is outside the repo/project scope.

**Comment by rsyring** [comment]
I'm open to creating an issue to eventually have an official Docker image that we support.  However, given our limited resources and the large backlog we have, I don't want to have another platform/environment that we are committed to maintaining.  Therefore, I'm going to close this PR.

@bugra You are welcome to open an issue to request the creation of an official Docker image for pymssql.  I actually think that would be a good idea if it seems like something that is easily supported by the limited team we have working on pymssql.  If we do support it, I'd be inclined to have that be in a different repot --> "github.com/pymssql/docker"

**Comment by AlexHagerman** [comment]
@bugra I'm traveling for an adoption right now, so progress on the release has slowed a bit. I should be home next week and progress will resume at a more regular speed. The primary blocker right now is building the `manylinux wheels`.

2.1.4 RC 1 could potentially be available on pypi by the end of the week once the manylinux wheels have been built. I've started working on that locally, but it's not something I have experience with. If you do and you want to build them while documenting that process then that would speed things up. The documentation would help because I can begin integrating that into the CircleCI build/deploy pipeline we are moving to after the 2.1.4 release.

https://github.com/pypa/manylinux
https://github.com/pypa/python-manylinux-demo

I have the docker images pulled, and a slightly modified build_wheels.sh I'm testing locally. Trying to get all the dependencies we rely on into the image since our Travis build was using apt and the manylinux image is CentOS 5 with yum. I'll turn that into a gist later when I can get my laptop out, or it will eventually be part of the build process in the repo.

Once the manylinux wheels are available we have the windows artifacts here: https://ci.appveyor.com/project/level12/pymssql/build/319 and I can pull those down then use twine to load to test.pypi.org and verify the RC has the pre release tag there. 

Once that's there I'll load the pre release to pypi.org and announce it on the mailing list. We will give it a few days for feedback on the RC then we can publish without the pre release flag.

Hope that helps provide a timeline of where we are. Any questions let me know. Is there something specific to 2.1.4 from 2.1.3 that you're needing, or just looking for a newer release?

**Comment by bugra** [comment]
@AlexHagerman That sounds perfect! 

Currently, I cannot install pip pymssql in an Alpine docker image and the reason why I am pushing on the new release because of this.

**Comment by AlexHagerman** [comment]
@bugra have you tried the RC announced last week?

**Comment by bugra** [comment]
@AlexHagerman I did and it is throwing a similar error and I am unable to build the docker image provided to this PR.

**Comment by JayRizzo** [comment]
Hi all,

Not sure if this is relevant to anyone... but,
for me, I was able to install by using this command.

    pip3 install git+https://github.com/pymssql/pymssql

I posted my answer on SO: https://stackoverflow.com/a/51608486/1896134

**Pull request closed without merging**
